module.exports = {
  RESOURCE_NOT_FOUND: 'Запрашиваемый ресурс не найден',
  OBJECT_NOT_FOUND: 'Запрашиваемый объект не найден',
  INVALID_LINK_URL: 'Инвалидный url ссылки',
  INVALID_IMAGE_URL: 'Инвалидный url изображения',
  INVALID_EMAIL: 'Инвалидный e-mail адрес',
  INVALID_CREDENTIALS: 'Неправильные почта или пароль',
  INVALID_PASSWORD: 'Неверный формат пароля',
  INVALID_NAME: 'Имя пользователя должно быть от 2 до 30 символов',
  INVALID_KEYWORDS: 'Длина ключевых слов не может превышать 30 символов',
  INVALID_TEXT: 'Текст не может быть пустым',
  INVALID_DATE: 'Некорректная дата',
  INVALID_SOURCE: 'Длина источника не может превышать 30 символов',
  INVALID_TITLE: 'Длина названия не может превышать 150 символов',
  BAD_REQUEST: 'Некорректный запрос',
  INTERNAL_ERROR: 'Внутренняя ошибка сервера',
  UNAUTHORIZED_ERROR: 'Необходимо пройти авторизацию',
  FORBIDDEN_ERROR: 'Вы не имеете прав на данную операцию',
  DEFAULT_ERROR: 'Что-то пошло не так',
  DUPLICATE_EMAIL: 'Пользователь с таким email уже существует',
  INVALID_ARTICLE_ID: 'Некорректный id статьи',
  CONFLICT_ERROR: 'Конфликтное обращение к ресурсу',
};
