module.exports = {
  RESOURCE_NOT_FOUND: 'Запрашиваемый ресурс не найден',
  OBJECT_NOT_FOUND: 'Запрашиваемый объект не найден',
  INVALID_LINK_URL: 'Инвалидный url ссылки',
  INVALID_IMAGE_URL: 'Инвалидный url изображения',
  INVALID_EMAIL: 'Инвалидный e-mail адрес',
  INVALID_CREDENTIALS: 'Неправильные почта или пароль',
  BAD_REQUEST: 'Некорректный запрос',
  INTERNAL_ERROR: 'Внутренняя ошибка сервера',
  UNAUTHORIZED_ERROR: 'Необходимо пройти авторизацию',
  FORBIDDEN_ERROR: 'Вы не имеете прав на данную операцию',
  DEFAULT_ERROR: 'Что-то пошло не так',
  DUPLICATE_EMAIL: 'Пользователь с таким email уже существует',
  INVALID_ARTICLE_ID: 'Некорректный id статьи',
  CONFLICT_ERROR: 'Конфликтное обращение к ресурсу',
};
